version: '3.8'
services:
  flask:
    build: ./server
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development

  react:
    build: ./client
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - flask
